# Generated by Django 4.2.2 on 2023-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
